stages:
  - build

# -------------------------------------------------------------------------
# Build stage
# -------------------------------------------------------------------------

#freebsd 11 build:
#  variables:
#    CI_DEBUG_TRACE: "true"
#  stage: build
#  tags:
#    - freebsd11
#  script:
#    - ls -al /


centos 7 build:
  stage: build
  tags:
    - os-manager
  image: registry.gitlab.com/egloo.ca/os-manager/builder-image:os7
  script:
    # Prep build directory
    - mkdir -p result centos7/builds centos7/logs
    - sudo yum -y install automake libtool
    # Build packages
    - ./autogen.sh
    - ./configure
    - make dist
    - rpmbuild -bs ./deploy/rpm/netify-fwa.spec --define "_sourcedir $PWD" --define "_srcrpmdir $PWD"
    - mock -v --old-chroot --resultdir=result *.src.rpm
    # Copy packages and logs to artifacts
    - grep -v DEBUG result/root.log
    - mv result/*rpm centos7/builds/
    - mv result/*log centos7/logs/
    - rm -rf result
  artifacts:
    when: always
    paths:
    - centos7
    expire_in: 1 day


centos 8 build:
  stage: build
  tags:
    - os-manager
  image: registry.gitlab.com/egloo.ca/os-manager/builder-image:os8
  script:
    # Prep build directory
    - mkdir -p result centos8/builds centos8/logs
    - sudo yum -y install automake libtool
    # Build packages
    - ./autogen.sh
    - ./configure
    - make dist
    - rpmbuild -bs ./deploy/rpm/netify-fwa.spec --define "_sourcedir $PWD" --define "_srcrpmdir $PWD"
    - mock -v --old-chroot --resultdir=result *.src.rpm
    # Copy packages and logs to artifacts
    - grep -v DEBUG result/root.log
    - mv result/*rpm centos8/builds/
    - mv result/*log centos8/logs/
    - rm -rf result
  artifacts:
    when: always
    paths:
    - centos8
    expire_in: 1 day

debian 10 build:
  stage: build
  image: debian:10
  script:
    # Prep build directory
    - mkdir -p debian10/builds debian10/logs
    - apt install -y automake libtool pkg-config
    # Build packages
    - ./autogen.sh
    - ./configure
    - make dist-gzip
    # Copy packages and logs to artifacts
    - mv *.tar.gz debian10/builds/
    - mv config.log debian10/logs/
  artifacts:
    when: always
    paths:
    - debian10
    expire_in: 1 day

# -------------------------------------------------------------------------
# Test stage
# -------------------------------------------------------------------------

#pfsense 2.4.x test:
#  stage: test
#  tags:
#    - pfsense24
#  script:
#    - ls -al /

#clearos 7 test:
#  stage: test
#  tags:
#    - os-manager
#  image: centos:7
#  script:
#    - rpm -Uvh http://mirrors.egloo.ca/egloo/clearos/7/devel/staging/clearos-release-7-current.noarch.rpm
#    - rpm --import http://download.netify.ai/netify/clearos/7/testing/RPM-GPG-KEY-netify
#    - curl http://download.netify.ai/netify/clearos/7/netify.repo --output /etc/yum.repos.d/netify.repo 
#    - yum -y --nogpgcheck --enablerepo=clearos-centos,clearos-centos-updates,clearos-contribs-testing,netify-testing localinstall centos7/builds/*.rpm
