stages:
  - build

# -------------------------------------------------------------------------
# Build stage
# -------------------------------------------------------------------------

openwrt 19.07 build:
  stage: build
  tags:
    - docker
  image: debian:10
  script:
    # Prep build directory
    - apt update
    - apt install -y rsync autoconf automake make libtool pkg-config
    # Build packages
    - ./autogen.sh
    - ./configure --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var
    - sh ./deploy/openwrt/package/make-package.sh 0.$CI_COMMIT_SHORT_SHA
    # Copy packages to artifacts and rsync to mirror
    - mkdir -p builds/netify-fwa/openwrt/19.07/noarch
    - mv openwrt-package/netify-fwa-*.ipk builds/netify-fwa/openwrt/19.07/noarch/
    - rsync -rtv builds/* master-mirror.egloo.ca::netify-builds/
  artifacts:
    when: always
    paths:
    - builds
    expire_in: 30 days

# -------------------------------------------------------------------------
# Test stage
# -------------------------------------------------------------------------

#pfsense 2.4.x test:
#  stage: test
#  tags:
#    - pfsense24
#  script:
#    - ls -al /

#clearos 7 test:
#  stage: test
#  tags:
#    - os-manager
#  image: centos:7
#  script:
#    - rpm -Uvh http://mirrors.egloo.ca/egloo/clearos/7/devel/staging/clearos-release-7-current.noarch.rpm
#    - rpm --import http://download.netify.ai/netify/clearos/7/testing/RPM-GPG-KEY-netify
#    - curl http://download.netify.ai/netify/clearos/7/netify.repo --output /etc/yum.repos.d/netify.repo 
#    - yum -y --nogpgcheck --enablerepo=clearos-centos,clearos-centos-updates,clearos-contribs-testing,netify-testing localinstall centos7/builds/*.rpm
